name: Python Release

on:
  push:
    tags:
      - python-v*

jobs:
  create_source_dist:
    name: Create sdist package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install Tox
        run: pip install tox
      - name: Build sdist
        working-directory: ./bindings/python
        run: tox -e build-sdist
      - uses: actions/upload-artifact@v2
        with:
          name: Distribution Artifacts
          path: bindings/python/dist/

  create_macos_and_windows_wheels:
    name: Wheels for Python ${{ matrix.python-version }} / ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python-version: ['3.5', '3.6', '3.7', '3.8']
        architecture: [x64]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install Tox
        run: pip install tox
      - name: Build wheel
        working-directory: ./bindings/python
        run: tox -e build-wheel
      - uses: actions/upload-artifact@v2
        with:
          name: Distribution Artifacts
          path: bindings/python/dist/

  create_wheels_manylinux:
    name: Wheels for Python ${{ matrix.PYTHON_IMPLEMENTATION_ABI }} / Linux
    strategy:
      fail-fast: false
      matrix:
        # List of the language version - ABI pairs to publish wheels for
        # The list of supported is obtainable by running
        # `docker run quay.io/pypa/manylinux2014_x86_64 ls /opt/python`
        # Read more about compatibility tags in PEP 425
        # https://www.python.org/dev/peps/pep-0425/
        PYTHON_IMPLEMENTATION_ABI: [cp35-cp35m, cp36-cp36m, cp37-cp37m, cp38-cp38]
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    env:
      # Variable needed for PyO3 to properly identify the python interpreter
      PYTHON_SYS_EXECUTABLE: /opt/python/${{ matrix.PYTHON_IMPLEMENTATION_ABI }}/bin/python
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install Tox
        run: ${{ env.PYTHON_SYS_EXECUTABLE }} -m pip install tox
      - name: Build wheel
        working-directory: ./bindings/python
        run: |
          ${{ env.PYTHON_SYS_EXECUTABLE }} -m tox -e build-wheel
          # Ensure that the wheel is tagged as manylinux2014 platform
          auditwheel repair \
            --wheel-dir=./dist \
            --plat manylinux2014_x86_64 \
            ./dist/css_inline-*-${{ matrix.PYTHON_IMPLEMENTATION_ABI }}-linux_x86_64.whl
          # Remove `linux_x86_64` tagged wheels as they are not supported by PyPI
          rm ./dist/css_inline-*-${{ matrix.PYTHON_IMPLEMENTATION_ABI }}-linux_x86_64.whl
      - uses: actions/upload-artifact@v2
        with:
          name: Distribution Artifacts
          path: bindings/python/dist/